export const matches = [
  {
    matchId: 1,
    userId: 1,
    opponentId: 2,
    player1Points: 10,
    player2Points: 8,
    gameType: 'standard',
    finalResultString: '10-8',
  },
  {
    matchId: 2,
    userId: 3,
    opponentId: 4,
    player1Points: 10,
    player2Points: 9,
    gameType: 'ladder',
    finalResultString: '10-9',
  },
  {
    matchId: 3,
    userId: 4,
    opponentId: 5,
    player1Points: 3,
    player2Points: 7,
    gameType: 'standard',
    finalResultString: '3-7',
  },
  {
    matchId: 4,
    userId: 2,
    opponentId: 1,
    player1Points: 11,
    player2Points: 8,
    gameType: 'ladder',
    finalResultString: '11-8',
  },
  {
    matchId: 5,
    userId: 5,
    opponentId: 2,
    player1Points: 3,
    player2Points: 5,
    gameType: 'standard',
    finalResultString: '3-5',
  },
];
